### ISSUE TITLE
Most list methods do *not* mutate the list

### ISSUE THREAD

**Issue by gvwilson** [datacamp/courses-introduction-to-python#44]
Chapter 3 says that "most list methods will change the list they're called on". Better to change "most" to "some" (a quick count shows 50/50).

**Comment by machow** [comment]
It looks like 8 / 11 of a list's methods mutate

**Mutate**

'append',
 'clear',
 'extend',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort'

**Don't**

 'copy',
 'count',
 'index'

**Comment by hugobowne** [comment]
'Most' is an ambiguous term in this context. If it's 8 of 11, 'more than half' is both precise and correct. I would swap it out for the less ambiguous term.
